# Generated by Django 4.1.7 on 2024-04-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0003_fotosslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Precio del Producto'),
        ),
    ]
