# Generated by Django 4.1.7 on 2024-04-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0005_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='anexo_mascota',
        ),
        migrations.AddField(
            model_name='visita',
            name='mascota',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de Mascota'),
        ),
        migrations.AddField(
            model_name='visita',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Mascota'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='motivo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Motivo de Visita'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='nota',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notas adicionales'),
        ),
    ]
