# Generated by Django 4.1.7 on 2024-04-18 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veterinaria', '0007_tipoanimales'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motivo de Consulta')),
                ('diagnostico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Diagnóstico de Consulta')),
                ('tratamiento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tratamiento de Consulta')),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
            ],
            options={
                'verbose_name': 'HistoriaClinica',
                'verbose_name_plural': 'HistoriasClinicas',
            },
        ),
        migrations.RemoveField(
            model_name='personal',
            name='anexo_tipo',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='anexo_usuarios',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='usuario_modificacion',
        ),
        migrations.RemoveField(
            model_name='tipousuario',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='tipousuario',
            name='usuario_modificacion',
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='anexo_visita',
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='usuario_modificacion',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='anexo_mascota',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='usuario_modificacion',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='propietarios',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='correo',
        ),
        migrations.AddField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Propietario'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='anexo_usuarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUsuariosPropietario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Diagnostico',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
        migrations.DeleteModel(
            name='Tratamiento',
        ),
        migrations.DeleteModel(
            name='Vacuna',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='anexo_mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoMascota', to='veterinaria.mascota'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionHistoriaClinica', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModHistoriaClinica', to=settings.AUTH_USER_MODEL),
        ),
    ]
