# Generated by Django 4.1.7 on 2024-04-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0008_historiaclinica_remove_personal_anexo_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Diagnóstico de Consulta'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='motivo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Motivo de Consulta'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='observaciones',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='tratamiento',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tratamiento de Consulta'),
        ),
    ]
