# Generated by Django 4.1.7 on 2024-04-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0009_alter_historiaclinica_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Edad de Mascota'),
        ),
    ]
