# Generated by Django 4.1.7 on 2024-04-27 19:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veterinaria', '0010_alter_mascota_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='usuario_creacion',
        ),
        migrations.AddField(
            model_name='mascota',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mascota',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Color de Mascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='mascota',
            name='peso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Peso de Mascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sexo de Mascota'),
        ),
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria del Producto'),
        ),
        migrations.AddField(
            model_name='productos',
            name='fecha_ingreso',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='productos',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='productos',
            name='tipo_producto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo del Producto'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Doctor')),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidad del Doctor')),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('fecha_hora_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Creación')),
                ('fecha_hora_modificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Modificación')),
                ('anexo_usuarios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnexoUsuariosDoctor', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsercreacionDoctor', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserModDoctor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
    ]
